### PR TITLE
Fix mandelbrot example results

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by GabrielMajeri** [comment]
We might want to disable FMA globally for mandelbrot (maybe keep the `mul_adde`, but disable it when testing, and warn users it gives different results).

The other benchmarksgame implementations [also disable it](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/mandelbrot-gpp-6.html) (acknowledging it gives different results from the official ones, yet it's faster).

**Comment by gnzlbg** [comment]
So I am going to merge this once CI is green. 

What I'd prefer to do is optimize the version without fma as much as possible, and just provide `simd_fma` and `simd_fma_par` versions that do use fma, but that we don't validate against the benchmarks game results (or we allow a tolerance or something). I think it is still interesting to benchmarks these though. 

What do you think?

**Comment by GabrielMajeri** [comment]
@gnzlbg Since the benchmarksgame's target CPU is a `core2` we don't even have to worry about FMA for it. So for the `verify_simd_output` test we could build with `-C target-cpu=core2`, because that's how the original output was obtained.

And then, for the other tests, we can simply compare ISPC's output with our SIMD output. We can just assume that ISPC generates valid results.

I think adding (yet another) version for this algorithm is unnecessary:

- Most people who will play around with the example don't need exact results, just a final image which looks like the mandelbrot fractal.

- Anyone who is trying to submit this to the benchmarksgames would know beforehand what `target-cpu` to profile and benchmark for.

**Comment by gnzlbg** [comment]
@GabrielMajeri we can use `mul_adde` here, and then only test against the benchmark game results if `fma` is not available (e.g. `#[cfg(not(target_feature = "fma"))]` or `! is_x86_feature_detected!("fma")` or similar .

**Pull request merged**
