### PR TITLE
add shuffle_bytes to unsigned integer vectors

### LINKED ISSUE #46: Portable shuffles with run-time indices
There is some support on ARM and x86 for shuffles with run-time indices for some vector types:

* `arm` / `aarch64`: NEON has vector table lookup intrinsics: `vtbl{1,2,3,4}`
* `x86` / `x86_64`: SSSE3 `pshufb`, AVX: `vpermilp{s,d}`, `vperm2f128`, AVX2: `vpshufb`, AVX2/AVX-512F: `vperm{d,s}`, AVX-512F+VL: `vpermt2d`

We should at least consider whether offering a portable way of abstracting over these is worth pursuing. The API could look like this: 

```rust
impl {element_type}{element_width}x{number_of_lanes} {
    fn shuffle(self, indices: Self) -> Self {
        let mut result = Default::default();
        for i in 0..Self::lanes() {
            result = result.replace(i, self.extract(indices.extract(i) as usize));
        }
        result
    }
}
```

Independently of how good code-generation is for this (we can always file bugs and add our own workarounds here and there), would something like this be worth pursuing? 

We could also scale this down to a `shuffle_bytes` portable operation that is only implemented for unsigned integer vector types (`uMxN`) since that is what appears to be most widely supported (we could always revisit the full shuffles with run-time indices in the future).

cc @sunfish @TheIronBorn @rkruppe

### PR DESCRIPTION
**Pull request by gnzlbg**
Closes #46 .

### CODE REVIEW

**Comment by TheIronBorn** [comment]
Curious why you don’t use `_mm_shuffle_pi8` for `u8x8`

**Comment by gnzlbg** [comment]
Because I am a moron. I was looking for this for like 5 minutes thinking it would be part of MMX...

**Comment by TheIronBorn** [comment]
Oh and `_mm256_shuffle_epi8`?

**Comment by gnzlbg** [comment]
`_mm256_shuffle_epi8` operates on two 128-bit halves of a 256-bit vector independently.. many AVX intrinsics do this, I really dislike that.

**Comment by TheIronBorn** [comment]
It's counter-intuitive and doesn't seem very useful. Oh well

**Comment by gnzlbg** [comment]
@TheIronBorn let me know if you want to send a PR fixing `u8x8`.

**Pull request merged**
